<template>
  <section class="ops">
    <div class="actions"><strong>预置业务动作</strong><span><el-button @click="openApiImport">导入 OpenAPI</el-button><el-button type="primary" @click="openEditor()">新增动作</el-button></span></div>
    <el-table :data="items" v-loading="loading" border>
      <el-table-column prop="operation_name" label="业务动作" />
      <el-table-column prop="path" label="相对路径" min-width="220" show-overflow-tooltip />
      <el-table-column label="动作类型"><template #default="{ row }">{{ row.method === 'POST' ? '查询' : '查询' }}</template></el-table-column>
      <el-table-column prop="status" label="状态" />
      <el-table-column label="操作"><template #default="{ row }"><el-button v-if="editable(row)" link @click="openEditor(row)">编辑</el-button><el-button v-if="editable(row)" link @click="openTest(row)">测试</el-button><el-button v-if="['TESTED', 'PENDING_APPROVAL'].includes(row.status)" link type="success" @click="publish(row)">发布</el-button><el-button v-if="row.status === 'PUBLISHED'" link type="danger" @click="disable(row)">停用</el-button></template></el-table-column>
    </el-table>
    <el-dialog v-model="editorVisible" title="业务动作定义" width="820px" destroy-on-close>
      <el-steps :active="step" finish-status="success" simple><el-step title="基础信息" /><el-step title="请求参数" /><el-step title="返回字段" /><el-step title="错误与脱敏" /><el-step title="测试发布" /></el-steps>
      <el-form v-show="step === 0" :model="editor" label-width="100px" class="step-form"><el-form-item label="动作编码" required><el-input v-model="editor.operation_code" :disabled="Boolean(editor.id)" /></el-form-item><el-form-item label="动作名称" required><el-input v-model="editor.operation_name" /></el-form-item><el-form-item label="查询方式"><el-radio-group v-model="editor.method"><el-radio value="GET">直接查询</el-radio><el-radio value="POST">条件查询</el-radio></el-radio-group></el-form-item><el-form-item label="相对路径" required><el-input v-model="editor.path" placeholder="例如 /open-apis/contact/v3/users" /><div class="form-hint">相对路径将与接入类型的基础 URL 拼接；请勿填写域名、协议或 Header。</div></el-form-item><el-alert title="基础 URL、域名白名单、认证和技术 Header 由接入类型统一托管。" type="info" :closable="false" /></el-form>
      <div v-show="step === 1" class="step-form"><FieldEditor v-model="editor.inputFields" title="请求业务字段" /></div>
      <div v-show="step === 2" class="step-form"><FieldEditor v-model="editor.outputFields" title="返回业务字段" :allow-sensitive="true" /></div>
      <div v-show="step === 3" class="step-form"><el-alert title="敏感字段不会保存到样本和测试结果中。" type="warning" :closable="false" /><el-table :data="editor.errorRules" size="small" border style="margin-top:12px"><el-table-column label="状态码"><template #default="{ row }"><el-input-number v-model="row.status_code" :min="100" :max="599" /></template></el-table-column><el-table-column label="错误码"><template #default="{ row }"><el-input v-model="row.error_code" /></template></el-table-column><el-table-column label="业务提示"><template #default="{ row }"><el-input v-model="row.message" /></template></el-table-column><el-table-column width="70"><template #default="{ $index }"><el-button link type="danger" @click="editor.errorRules.splice($index, 1)">删除</el-button></template></el-table-column></el-table><el-button link type="primary" @click="editor.errorRules.push({ status_code: 404, error_code: '', message: '未找到符合条件的业务数据', priority: 0 })">新增错误规则</el-button></div>
      <div v-show="step === 4" class="step-form"><el-result icon="info" title="使用已有系统进行连接测试" sub-title="测试将使用所选系统的有效凭证发起只读请求；填写的参数只用于本次测试。"><template #extra><el-form v-if="editor.id" :model="testParameters" label-width="110px" style="max-width:520px;text-align:left"><el-form-item label="测试系统" required><el-select v-model="testSystemId" placeholder="选择已配置凭证的系统" style="width:100%"><el-option v-for="system in testSystems" :key="system.id" :label="system.system_name" :value="system.id" /></el-select></el-form-item><el-form-item v-for="field in requiredFields" :key="field.field_id" :label="field.label" required><el-input v-model="testParameters[field.field_id]" /></el-form-item><el-button type="primary" @click="runTest(editor)">测试</el-button></el-form></template></el-result></div>
      <template #footer><el-button :disabled="step === 0" @click="step--">上一步</el-button><el-button v-if="step < 4" type="primary" @click="step++">下一步</el-button><el-button v-else type="primary" @click="save">保存草稿</el-button></template>
    </el-dialog>
    <el-dialog v-model="openApiVisible" title="导入 OpenAPI" width="680px"><el-input v-model="openApiText" type="textarea" :rows="9" placeholder="粘贴 OpenAPI 3.x 文档以转换为动作草稿" /><el-button style="margin:10px 0" @click="preview">预览</el-button><el-checkbox-group v-model="chosen"><el-checkbox v-for="item in candidates" :key="item.operation_id" :label="item.operation_id">{{ item.template_name }}</el-checkbox></el-checkbox-group><template #footer><el-button @click="openApiVisible=false">取消</el-button><el-button type="primary" @click="importOpenApi">导入草稿</el-button></template></el-dialog>
  </section>
</template>
<script setup lang="ts">
import { computed, defineComponent, h, onMounted, reactive, ref } from 'vue'
import { ElButton, ElCheckbox, ElInput, ElInputNumber, ElTable, ElTableColumn } from 'element-plus'
import { ElMessage } from 'element-plus'
import { ucpApi } from '@/api/ucp'

type Field = { field_id: string; label: string; type: string; required: boolean; sensitive: boolean }
const FieldEditor = defineComponent({ props: { modelValue: { type: Array, required: true }, title: { type: String, required: true }, allowSensitive: Boolean }, emits: ['update:modelValue'], setup(props, { emit }) { const rows = () => props.modelValue as Field[]; const add = () => emit('update:modelValue', [...rows(), { field_id: '', label: '', type: 'string', required: false, sensitive: false }]); const update = (index: number, key: keyof Field, value: unknown) => { const next = [...rows()]; next[index] = { ...next[index], [key]: value }; emit('update:modelValue', next) }; const remove = (index: number) => emit('update:modelValue', rows().filter((_, rowIndex) => rowIndex !== index)); return () => h('div', [h('div', { class: 'field-title' }, [props.title, h(ElButton, { link: true, type: 'primary', onClick: add }, () => '新增字段')]), h(ElTable, { data: rows(), border: true, size: 'small' }, () => [h(ElTableColumn, { label: '字段编码' }, { default: ({ row, $index }: any) => h(ElInput, { modelValue: row.field_id, 'onUpdate:modelValue': (value: string) => update($index, 'field_id', value) }) }), h(ElTableColumn, { label: '展示名称' }, { default: ({ row, $index }: any) => h(ElInput, { modelValue: row.label, 'onUpdate:modelValue': (value: string) => update($index, 'label', value) }) }), h(ElTableColumn, { label: '类型', width: 120 }, { default: ({ row, $index }: any) => h('select', { value: row.type, onChange: (event: Event) => update($index, 'type', (event.target as HTMLSelectElement).value) }, ['string', 'number', 'integer', 'boolean', 'date'].map(type => h('option', { value: type }, type))) }), h(ElTableColumn, { label: '必填', width: 70 }, { default: ({ row, $index }: any) => h(ElCheckbox, { modelValue: row.required, 'onUpdate:modelValue': (value: unknown) => update($index, 'required', Boolean(value)) }) }), props.allowSensitive ? h(ElTableColumn, { label: '敏感', width: 70 }, { default: ({ row, $index }: any) => h(ElCheckbox, { modelValue: row.sensitive, 'onUpdate:modelValue': (value: unknown) => update($index, 'sensitive', Boolean(value)) }) }) : null, h(ElTableColumn, { width: 70 }, { default: ({ $index }: any) => h(ElButton, { link: true, type: 'danger', onClick: () => remove($index) }, () => '删除') })].filter(Boolean))]) } })
const props = defineProps<{ packageCode: string; packageId: number }>(); const emit = defineEmits(['changed']); const items = ref<any[]>([]); const testSystems = ref<any[]>([]); const testSystemId = ref<number>(); const loading = ref(false); const editorVisible = ref(false); const openApiVisible = ref(false); const openApiText = ref(''); const candidates = ref<any[]>([]); const chosen = ref<string[]>([]); const step = ref(0)
const empty = () => ({ id: 0, operation_code: '', operation_name: '', method: 'GET', path: '', inputFields: [] as Field[], outputFields: [] as Field[], errorRules: [] as any[] })
const editor = reactive<any>(empty()); const testParameters = reactive<Record<string, string>>({}); const requiredFields = computed(() => fieldsFromSchema(editor.input_schema || toSchema(editor.inputFields)).filter(field => field.required)); const editable = (row: any) => ['DRAFT', 'FAILED'].includes(row.status); const fieldsFromSchema = (schema: any): Field[] => Object.entries(schema?.properties || {}).map(([field_id, value]: [string, any]) => ({ field_id, label: value.title || field_id, type: value.type || 'string', required: (schema.required || []).includes(field_id), sensitive: Boolean(value.sensitive) })); const toSchema = (fields: Field[]) => ({ type: 'object', properties: Object.fromEntries(fields.map(field => [field.field_id, { type: field.type, title: field.label, sensitive: field.sensitive }])), required: fields.filter(field => field.required).map(field => field.field_id) })
async function load() { loading.value = true; try { items.value = await ucpApi.packageOperations(props.packageCode) } finally { loading.value = false } }
function openEditor(row?: any) { Object.assign(editor, empty(), row || {}, row ? { inputFields: fieldsFromSchema(row.input_schema), outputFields: fieldsFromSchema(row.output_schema), errorRules: row.error_rules || [] } : {}); Object.keys(testParameters).forEach(key => delete testParameters[key]); step.value = 0; editorVisible.value = true } async function openTest(row: any) { openEditor(row); testSystems.value = (await ucpApi.systems()).items.filter((item: any) => item.package_id === props.packageId); testSystemId.value = testSystems.value[0]?.id; step.value = 4 }
async function save() { try { const path = String(editor.path || '').trim(); if (!editor.operation_code || !editor.operation_name || !path) return ElMessage.error('请填写动作编码、名称和相对路径'); if (!path.startsWith('/')) return ElMessage.error('相对路径必须以 / 开头'); const requestTemplate = Object.fromEntries(editor.inputFields.map((field: Field) => [field.field_id, `{{${field.field_id}}}`])); const payload = { operation_code: editor.operation_code, operation_name: editor.operation_name, object_code: 'CUSTOM', method: editor.method, path, input_schema: toSchema(editor.inputFields), output_schema: toSchema(editor.outputFields), error_rules: editor.errorRules, query_config: editor.method === 'GET' ? requestTemplate : {}, body_template: editor.method === 'POST' ? requestTemplate : undefined }; if (editor.id) await ucpApi.updatePackageOperation(props.packageCode, editor.id, payload); else await ucpApi.createPackageOperation(props.packageCode, payload); editorVisible.value = false; await load(); emit('changed') } catch (error: any) { ElMessage.error(error?.response?.data?.detail || '保存失败') } }
async function runTest(row: any) { const missing = requiredFields.value.filter(field => !testParameters[field.field_id]); if (missing.length) return ElMessage.error(`请填写测试参数：${missing.map(field => field.label).join('、')}`); if (!testSystemId.value) return ElMessage.error('请先选择已配置凭证的测试系统'); const result = await ucpApi.testPackageOperation(props.packageCode, row.id, { system_id: testSystemId.value, context: { ...testParameters } }); result.status === 'SUCCESS' ? ElMessage.success(result.message) : ElMessage.error(result.message || '测试失败'); editorVisible.value = false; await load() }
async function publish(row: any) { await ucpApi.publishPackageOperation(props.packageCode, row.id); await load(); emit('changed') } async function disable(row: any) { await ucpApi.disablePackageOperation(props.packageCode, row.id); await load() } function openApiImport() { openApiText.value = ''; candidates.value = []; chosen.value = []; openApiVisible.value = true } async function preview() { try { const result = await ucpApi.previewPackageOpenApi(props.packageCode, JSON.parse(openApiText.value)); candidates.value = result.operations; chosen.value = result.operations.map((item: any) => item.operation_id) } catch { ElMessage.error('OpenAPI 文档格式无效') } } async function importOpenApi() { await ucpApi.importPackageOpenApi(props.packageCode, { document: JSON.parse(openApiText.value), selected_operation_ids: chosen.value }); openApiVisible.value = false; await load() } onMounted(load)
</script>
<style scoped>.ops{margin-top:18px}.actions{display:flex;justify-content:space-between;margin-bottom:10px}.actions span{display:flex;gap:8px}.step-form{margin-top:20px;min-height:280px}.field-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.form-hint{margin-top:6px;color:#909399;font-size:12px;line-height:1.5}.el-checkbox-group{display:grid;gap:8px}</style>
