"""Make DWD technical ids target-owned and auto-generated."""
from alembic import op
import sqlalchemy as sa


revision = "0179_dwd_id_identity"
down_revision = "0178_cost_allocation_canonical_trigger"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    bind.execute(sa.text("""
        DO $$
        DECLARE
            target RECORD;
            default_expr TEXT;
            sequence_name TEXT;
            max_id BIGINT;
        BEGIN
            FOR target IN
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_type = 'BASE TABLE'
                  AND table_name LIKE 'dwd\\_%' ESCAPE '\\'
            LOOP
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = target.table_name
                      AND column_name = 'id'
                ) THEN
                    CONTINUE;
                END IF;

                SELECT column_default
                INTO default_expr
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = target.table_name
                  AND column_name = 'id';

                IF default_expr IS NULL THEN
                    EXECUTE format(
                        'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
                        target.table_name
                    );
                END IF;

                sequence_name := pg_get_serial_sequence(target.table_name, 'id');
                IF sequence_name IS NULL THEN
                    CONTINUE;
                END IF;

                EXECUTE format('SELECT MAX(id) FROM %I', target.table_name)
                INTO max_id;
                IF max_id IS NULL THEN
                    EXECUTE format('SELECT setval(%L::regclass, 1, false)', sequence_name);
                ELSE
                    EXECUTE format('SELECT setval(%L::regclass, %s, true)', sequence_name, max_id);
                END IF;
            END LOOP;
        END $$;
    """))


def downgrade() -> None:
    pass