<template><Teleport to="body"><div v-if="open" class="prompt-modal__mask" @click.self="close"><section class="prompt-modal" role="dialog" aria-modal="true"><header class="prompt-modal__header"><div class="prompt-modal__title">添加提示</div></header><button class="prompt-modal__close" type="button" aria-label="关闭" @click="close">×</button><div class="prompt-modal__body"><div class="prompt-field"><div class="prompt-field__label">标题</div><input v-model="draftTitle" class="prompt-input" type="text" /></div><div class="prompt-field"><div class="prompt-field__label">提示内容<span class="prompt-required">*</span></div><div class="prompt-textarea-wrap"><textarea v-model="draftContent" class="prompt-textarea" maxlength="2000" /><span class="prompt-count">{{ draftContent.length }}/2000</span></div></div><div class="prompt-field"><div class="prompt-field__label">颜色<span class="prompt-required">*</span></div><PerformancePromptColorPicker v-model="draftColor" /></div><div class="prompt-field"><div class="prompt-field__label">适用的被评估人范围<span class="prompt-required">*</span></div><div class="prompt-radio-group"><label class="prompt-radio"><input v-model="draftScope" type="radio" value="all" /><span class="prompt-radio__dot"></span><span>全部成员</span></label><label class="prompt-radio"><input v-model="draftScope" type="radio" value="cycle" /><span class="prompt-radio__dot"></span><span>在周期提示范围中配置具体范围</span></label></div></div></div><footer class="prompt-modal__footer"><button class="prompt-confirm" type="button" @click="confirm">确定</button><button class="prompt-cancel" type="button" @click="close">取消</button></footer></section></div></Teleport></template>
<script setup lang="ts">
import { ref, watch } from 'vue'
import PerformancePromptColorPicker from './PerformancePromptColorPicker.vue'
const props = defineProps<{ open: boolean }>()
const emit = defineEmits<{ 'update:open': [value: boolean]; save: [value: { title: string; content: string; color: string; scope: string }] }>()
const draftTitle=ref(''); const draftContent=ref(''); const draftColor=ref('#3B82F6'); const draftScope=ref('all')
watch(() => props.open, v => { if (v) { draftTitle.value=''; draftContent.value=''; draftColor.value='#3B82F6'; draftScope.value='all' } })
function close(){emit('update:open',false)} function confirm(){if(!draftContent.value.trim())return;emit('save',{title:draftTitle.value,content:draftContent.value,color:draftColor.value,scope:draftScope.value});close()}
</script>
<style scoped>.prompt-modal__mask{position:fixed;inset:0;z-index:1000;display:flex;align-items:center;justify-content:center;background:rgba(31,35,41,.45)}.prompt-modal{position:relative;display:flex;flex-direction:column;width:600px;max-height:calc(100% - 64px);box-sizing:border-box;border-radius:8px;background:#fff;color:#1f2329;font:400 14px/22px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue","PingFang SC","Microsoft YaHei",sans-serif}.prompt-modal__header{padding:24px}.prompt-modal__title{font-size:16px;font-weight:600}.prompt-modal__close{position:absolute;top:24px;right:24px;border:0;background:transparent;font-size:24px}.prompt-modal__body{overflow:auto;margin-bottom:24px;padding:0 24px}.prompt-field{margin-bottom:20px}.prompt-field__label{display:flex;min-height:22px;margin-bottom:8px;font-weight:600}.prompt-required{margin-left:2px;color:#f54a45}.prompt-input,.prompt-textarea{width:100%;box-sizing:border-box;border:.666667px solid #d0d3d6;border-radius:6px;background:#fff;font:inherit}.prompt-input{height:32px;padding:4px 11px}.prompt-textarea-wrap{position:relative}.prompt-textarea{height:49.3333px;padding:4px 11px 22px}.prompt-count{position:absolute;right:8px;bottom:4px;color:#8f959e;font-size:10px}.prompt-radio-group{display:flex;flex-direction:column;gap:8px}.prompt-radio{position:relative;display:flex;align-items:center;gap:8px;min-height:22px;color:#1f2329;line-height:22px;cursor:pointer}.prompt-radio input{position:absolute;top:11px;left:0;z-index:1;width:16px;height:16px;margin:0;opacity:0;transform:translateY(-8px);cursor:pointer}.prompt-radio__dot{display:block;width:16px;height:16px;flex:none;box-sizing:border-box;border:.666667px solid #8f959e;border-radius:50%}.prompt-radio input:checked+.prompt-radio__dot{border-color:#1456f0;background:#1456f0;box-shadow:inset 0 0 0 4px #fff}.prompt-modal__footer{display:flex;justify-content:flex-end;gap:8px;padding:0 24px 24px}.prompt-confirm,.prompt-cancel{height:32px;padding:4px 16px;border-radius:6px;font:inherit}.prompt-confirm{border:1px solid #3370ff;background:#3370ff;color:#fff}.prompt-cancel{border:1px solid #d0d3d6;background:#fff}</style>
