<template>
  <div class="performance-rich-text-box" :class="{ 'is-readonly': readonly, 'performance-rich-text-box--task-entry': variant === 'task-entry' }">
    <PerformanceRichTextToolbar :readonly="readonly" :active="active" @before-command="$emit('before-command', $event)" @command="$emit('command', $event)" />
    <div class="performance-rich-text-box__content"><slot /></div>
  </div>
</template>
<script setup lang="ts">
import PerformanceRichTextToolbar from './PerformanceRichTextToolbar.vue'
type CommandKey = 'bold' | 'italic' | 'underline' | 'insertOrderedList' | 'insertUnorderedList' | 'link'
withDefaults(defineProps<{ readonly?: boolean; active?: Partial<Record<CommandKey, boolean>>; variant?: 'default' | 'task-entry' }>(), { readonly: false, active: () => ({}), variant: 'default' })
defineEmits<{ command: [CommandKey]; 'before-command': [CommandKey] }>()
</script>
<style scoped>
.performance-rich-text-box{position:relative;min-height:130px;overflow:visible;border:1px solid #d0d3d6;border-radius:6px;background:#fff}.performance-rich-text-box:focus-within{border-color:#3370ff;box-shadow:0 0 0 2px rgba(51,112,255,.12)}.performance-rich-text-box__content{min-height:90px;max-height:none}.performance-rich-text-box :deep(.performance-rich-toolbar){border-bottom:1px solid #eff0f1}.performance-rich-text-box__content :deep(.rich-input){min-height:90px;padding:6px 10px;box-sizing:border-box;outline:0;font:400 14px/22px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"PingFang SC","Microsoft YaHei",sans-serif}.performance-rich-text-box__content :deep(.rich-input:empty:before){color:#8f959e;content:attr(data-placeholder)}.performance-rich-text-box__content :deep(.ace-line){min-height:22px;margin:0}.performance-rich-text-box--task-entry{min-height:124px;padding-bottom:12px;box-sizing:border-box;color:rgba(0,0,0,.65);font:400 14px/21px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue","PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";cursor:default}.performance-rich-text-box--task-entry:not(.is-readonly):not(.invalid):hover,.performance-rich-text-box--task-entry:not(.is-readonly):not(.invalid):focus-within{border-color:#1456f0;box-shadow:none}.performance-rich-text-box--task-entry .performance-rich-text-box__content{display:flex;min-height:88px;max-height:none;flex-direction:column;overflow:visible}.performance-rich-text-box--task-entry :deep(.performance-rich-toolbar){height:36px;gap:0;padding:6px 8px 6px 4px;border-bottom:0}.performance-rich-text-box--task-entry :deep(.performance-rich-toolbar button){margin:0 4px;border-radius:6px}.performance-rich-text-box--task-entry .performance-rich-text-box__content :deep(.rich-input){width:100%;min-height:88px;flex:1;padding:4px 11px;font:400 14px/22px -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue","PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"}.performance-rich-text-box__content :deep(.rich-input[contenteditable="true"]){cursor:text}.performance-rich-text-box__content :deep(.rich-input[contenteditable="false"]){cursor:default}.performance-rich-text-box--task-entry.invalid:hover,.performance-rich-text-box--task-entry.invalid:focus-within{border-color:#f54a45;box-shadow:none}
.performance-rich-text-box__content :deep(.rich-input ol),.performance-rich-text-box__content :deep(.rich-input ul){margin:0;padding:0 0 0 24px}.performance-rich-text-box__content :deep(.rich-input li){min-height:22px;margin:0;padding:0}.performance-rich-text-box__content :deep(.rich-input ol>li::marker){color:#646a73}.performance-rich-text-box__content :deep(.rich-input ul>li::marker){color:#3370ff}
</style>
